### ISSUE TITLE
How to deploy to the server?

### ISSUE THREAD

**Issue by sfvsfv** [Giac3/freeGPT-frontend#1]
How to deploy to the server?Can you give me a tutorial ，thanks!

**Comment by Giac3** [comment]
Hello @sfvsfv , Sure thing in order to deploy the frontend part of the project you can use any provider you choose, like vercel, heroku, AWS S3. For this project I chose to go with Firebase hosting. It is completely free and easy to set up. 

In order to use this project before deploying you will need to set up and host your own backend proxy server which you will use to access the OpenAI API as the link being used in this application only accepts requests from my projects url. The code for the backend can be found at [https://github.com/Giac3/freeGPT-server](url) . Once you have the proxy server set up and deployed follow these steps in order to get the frontend deployed and let me know if you run into any problems.


1. Install the firebase-tools CLI by running `npm install -g firebase-tools`
2. login by running `firebase login`
3. In the project root run `firebase init`
4. select `❯◯ Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub Action deploys` by pressing space and then press enter to go to the next step
5. select `Create a new project ` and follow the steps to set up a new project or choose `Use an existing project ` if you already have one set up
6. when asked `What do you want to use as your public directory?` type 'dist' then press enter
7. when asked `Configure as a single-page app (rewrite all urls to /index.html)?` say 'y' then press enter
8. say no to all following questions
9. Now run `npm run build` and wait for your project to finish building. This will build your project into a dist folder which we specified earlier as our public directory.
10. once the build step has finished run `firebase deploy` to deploy your app

**Comment by Giac3** [comment]
Hello closing this now let me know if you need further help 😄
